
namespace HouseholdTasksOverview.Model.Repository.cs;
using System;
using HouseholdTasksOverview.Model.Entities;
using HouseholdTasksOverview.Model.Entities.cs;
using Microsoft.Extensions.Configuration;
using Npgsql;
using NpgsqlTypes;
public class RoomsRepository : BaseRepository

{
    public RoomsRepository(IConfiguration configuration) : base(configuration)
    { 
    }

    // --- GET ROOM BY ID ---
    public Room GetRoomById(int id)
    {
        NpgsqlConnection dbConn = null;
        try
        {
            dbConn = new NpgsqlConnection(ConnectionString);
            var cmd = dbConn.CreateCommand();
            cmd.CommandText = "SELECT * FROM rooms WHERE id = @id";
            cmd.Parameters.Add("@id", NpgsqlDbType.Integer).Value = id;

            var data = GetData(dbConn, cmd);
            if (data != null && data.Read())
            {
                return MapDataReaderToRoom(data);
            }
            return null;
        }
        finally
        {
            dbConn?.Close();
        }
    }

    // --- GET ALL ROOMS ---
    public List<Room> GetRooms()
    {
        NpgsqlConnection dbConn = null;
        var rooms = new List<Room>();
        try
        {
            dbConn = new NpgsqlConnection(ConnectionString);
            var cmd = dbConn.CreateCommand();
            cmd.CommandText = "SELECT * FROM rooms";

            var data = GetData(dbConn, cmd);
            if (data != null)
            {
                while (data.Read())
                {
                    rooms.Add(MapDataReaderToRoom(data));
                }
            }
            return rooms;
        }
        finally
        {
            dbConn?.Close();
        }
    }

    // --- INSERT NEW ROOM ---
    public bool InsertRoom(Room r)
    {
        NpgsqlConnection dbConn = null;
        try
        {
            dbConn = new NpgsqlConnection(ConnectionString);
            var cmd = dbConn.CreateCommand();
            
            // id is auto-generated by the database (SERIAL)
            cmd.CommandText = @"
                INSERT INTO rooms (household_id, name, description) 
                VALUES (@household_id, @name, @description)";

            AddParametersToCommand(cmd, r);

            bool result = InsertData(dbConn, cmd);
            return result;
        }
        finally
        {
            dbConn?.Close();
        }
    }

    // --- UPDATE EXISTING ROOM ---
    public bool UpdateRoom(Room r)
    {
        var dbConn = new NpgsqlConnection(ConnectionString);
        var cmd = dbConn.CreateCommand();
        cmd.CommandText = @"
            UPDATE rooms 
            SET household_id = @household_id, 
                name = @name, 
                description = @description 
            WHERE id = @id";

        AddParametersToCommand(cmd, r);
        cmd.Parameters.AddWithValue("@id", NpgsqlDbType.Integer, r.Id);

        bool result = UpdateData(dbConn, cmd);
        return result;
    }

    // --- DELETE ROOM ---
    public bool DeleteRoom(int id)
    {
        var dbConn = new NpgsqlConnection(ConnectionString);
        var cmd = dbConn.CreateCommand();
        cmd.CommandText = "DELETE FROM rooms WHERE id = @id";
        
        cmd.Parameters.AddWithValue("@id", NpgsqlDbType.Integer, id);
        
        bool result = DeleteData(dbConn, cmd);
        return result;
    }

    // --- HELPER METHODS ---
    private Room MapDataReaderToRoom(NpgsqlDataReader data)
    {
        return new Room
        {
            Id = Convert.ToInt32(data["id"]),
            HouseholdId = Convert.ToInt32(data["household_id"]),
            Name = data["name"].ToString(),
            // Handle nullable description safely
            Description = data["description"] != DBNull.Value ? data["description"].ToString() : null
        };
    }

    private void AddParametersToCommand(NpgsqlCommand cmd, Room r)
    {
        cmd.Parameters.AddWithValue("@household_id", NpgsqlDbType.Integer, r.HouseholdId);
        cmd.Parameters.AddWithValue("@name", NpgsqlDbType.Varchar, r.Name);
        
        // If Description is null or empty in C#, send DBNull.Value to PostgreSQL
        cmd.Parameters.AddWithValue("@description", NpgsqlDbType.Text, 
            !string.IsNullOrEmpty(r.Description) ? (object)r.Description : DBNull.Value);
    }
}

